name: Pipelines Execute
description: Run Pipelines Execute
inputs:
  working_directory:
    description: "The folder path to run Pipelines Execute in"
    required: true
  with_ssh_enabled:
    description: "Run the build with tmate ssh enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
    required: false
  terragrunt_command:
    description: "The terragrunt command to run"
    required: true
    default: "plan"
  token:
    description: "The GitHub token for downloading the Gruntwork Pipelines binary and modules"
    required: true
  # The following are required for the terragrunt action
  tg_version:
    description: "Terragrunt version to install."
    required: true
    default: "0.48.1"
  tf_version:
    description: "OpenTofu or Terraform version to install."
    required: true
    default: "1.6.1"
  tf_binary:
    description: "Whether to use opentofu or terraform as the binary."
    required: true
    default: "opentofu"
    options:
      - terraform
      - opentofu
  tg_execution_parallelism_limit:
    # https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#limiting-the-module-execution-parallelism
    description: "Maximum number of concurrently executed Terraform modules during Terragrunt execution"
    required: false
    default: "0" # Ignored by pipelines-execute
  pipelines_cli_version:
    description: "The version of the Gruntwork Pipelines CLI to use"
    required: true
  infra_live_repo:
    description: "The name of the infrastructure-live repo to execute in"
    required: true
  infra_live_directory:
    description: "The name of the directory containing the infrastructure-live repo on disk"
    required: true
  infra_live_repo_branch:
    description: "The branch of the infrastructure-live repo to execute in"
    required: true
  gruntwork_config:
    description: "Contents of the Gruntwork config file"
    required: true
  update_path_in_bash_profile:
    description: "Whether to update the PATH variable within the bash profile to utilize the installed Terraform and Terragrunt versions"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Enable debugging via ssh
      uses: mxschmitt/action-tmate@v3
      env:
        GH_TOKEN: ${{ inputs.token }}
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.with_ssh_enabled }}
      with:
        detached: true
    - name: Setup Mise Toml
      id: mise-toml
      shell: bash
      env:
        TF_VERSION: ${{ inputs.tf_version }}
        TG_VERSION: ${{ inputs.tg_version }}
        TF_BINARY: ${{ inputs.tf_binary }}
      run: |
        echo 'TOML<<EOF' >> "$GITHUB_OUTPUT"
        echo '[tools]' >> "$GITHUB_OUTPUT"
        echo "$TF_BINARY = \"$TF_VERSION\"" >> "$GITHUB_OUTPUT"
        echo "terragrunt = \"$TG_VERSION\"" >> "$GITHUB_OUTPUT"
        echo 'EOF' >> "$GITHUB_OUTPUT"
    - uses: jdx/mise-action@v2
      with:
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          mise_toml: "${{ steps.mise-toml.outputs.TOML }}"

    - name: Test Terraform, OpenTofu and Terragrunt
      shell: bash
      run: |
        terraform --version || echo
        tofu --version || echo
        terragrunt --version

    - name: Download Pipelines CLI
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        repo: "gruntwork-io/pipelines-cli"
        version: "tags/${{ inputs.pipelines_cli_version }}"
        file: "pipelines_linux_amd64"
        target: "/tmp/pipelines"
        token: ${{ inputs.token }}

    - name: Install Pipelines CLI
      shell: bash
      run: |
        sudo mv /tmp/pipelines /usr/local/bin/pipelines
        sudo chmod +x /usr/local/bin/pipelines

    - name: Load Machine User Name
      id: load_machine_user
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        echo "MACHINE_USER_NAME=$(gh api /user | jq .login)" >> "$GITHUB_OUTPUT"

    - name: Run Pipelines Execute
      id: execute
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        MACHINE_USER_NAME: ${{ steps.load_machine_user.outputs.MACHINE_USER_NAME }}
      run: |
        # CD Infra-live directory && Run Pipelines-execute
        cd ${{ inputs.infra_live_directory }}

        pipelines execute terragrunt \
          --working-directory ${{ inputs.working_directory }} \
          --command "${{ inputs.terragrunt_command }}" \
          --tg-parallelism-limit ${{ inputs.tg_execution_parallelism_limit }} \
          --infra-live-repo ${{ inputs.infra_live_repo }} \
          --infra-live-repo-branch ${{ inputs.infra_live_repo_branch }} \
          --deployment-branch ${{ env.DEPLOY_BRANCH_NAME }} \
          --gruntwork-config "${{ inputs.gruntwork_config }}"
          --terragrunt-tfpath "${{ inputs.tf_binary }}"
